openapi: "3.0.0"
info:
  title: "Shopify Admin API"
  description: "The REST Admin API lets you build apps and other integrations for the Shopify admin."
  version: "2023-07"
servers:
  - url: https://docteststore.myshopify.com
paths:
  /admin/api/2023-07/customers/{customer_id}/orders.json:
    get:
      summary: "Retrieves all orders belonging to a customer. The query string parameters that are available to the  Order resource are also available to this endpoint."
      description: "https://shopify.dev/docs/admin-api/rest/reference/customers/customer#orders-2020-01"
      parameters:
        - in: "path"
          name: "customer_id"
          required: true
          schema:
            type: "string"
          description: "customer_id"
      tags:
        - "customers"
        - "customer"
        - "customers/customer"
      responses:
        200:
          description: ""
      operationId: "deprecated_202307_get_customers_param_customer_id_orders"
